create table DBMS_course(
id int generated by default as identity,
name varchar(50) not null,
age varchar(50) not null,
address varchar(50) not null,
salary dec(15,2) not null,
primary key(id));

select * from DBMS_course

insert into DBMS_course (name,age,address,salary) values
('Hailey','24', 'New York', 50000);

select * from DBMS_course

create view DBMS_Quiz as
select id, name, age from DBMS_course;

select * from DBMS_Quiz

create view DBMS_Quiz2 as 
select id , name from DBMS_course 
where name = 'Jim';

select * from DBMS_Quiz2

alter view DBMS_Quiz2 rename to DBMS_QuizII;

select * from DBMS_QuizII;

Begin;
delete from DBMS_course where age='23';
COMMIT;

select * from DBMS_course;
ROLLBACK;

BEGIN
LOCK table DBMS_course in Access write mode;

create or replace function TotalRecords()
RETURNS integer as $total$
declare
total integer;

BEGIN
select count(*) into total from DBMS_course;
RETURN total;
END;
$total$ language plpgsql;


select TotalRecords();

create or replace function TotalSalary()
RETURNS integer as $total_salary$
declare
total_salary integer;

BEGIN
select SUM(salary) into total_salary from DBMS_course;
RETURN total_salary;
END;
$total_salary$ language plpgsql;

select TotalSalary();

create or replace function AvgSalary()
RETURNS integer as $avg_salary$
declare
avg_salary integer;

BEGIN
select AVG(salary) into avg_salary from DBMS_course;
RETURN avg_salary;
END;
$avg_salary$ language plpgsql;

select AvgSalary();
